### ISSUE TITLE
Missing files in this version according to Manual

### ISSUE THREAD

**Issue by phtaheri** [PINE-Lab/HAPPE#5]
Hi PINELab,

I just tried downloading this folder today. I have a Macbook, and I could not understand for the life of me what the Macbook Quarantine section meant. I tried multiple combinations and it didn't work. 

Also, several of the path names do not match up from the user guide to the HAPPE folder on here. 

For example: the folder itself is called HAPPE-master, and on the userguide it says HAPPE. 
I could not find: 
![image](https://user-images.githubusercontent.com/124298216/216442510-e3450801-2788-49a6-a3bb-aeb739f94ed5.png)

I could find generate and validate in their respective separate folders, but nothing for add-ons. 

When I went to run HAPPE, which in this folder is HAPPE_m3, not HAPPY_v2_m3, by the way, an error message popped up regarding where to set up the path. I clicked the option that allowed me to add another path. 

Overall, I'm having a lot of issues getting HAPPE to be set up properly, according to the userguide. Perhaps some things on the user guide are not relevant anymore? I don't know. I will bring this up to my advisor tomorrow as well. 

Thanks,
Parsa

**Comment by PINE-Lab** [comment]
Hi Parsa,
The User Guide is not yet up to date, as there are a lot of changes that need to be made. Instead of adding the folders specified in the guide to your path, add these instead:
In the Set Path window that opens, use the Add Folder button to add the following folders (Please note that if you are using a Mac, \ will be replaced with /):
•	HAPPE
•	HAPPE\1. pre-process
•	HAPPE\2. check
•	HAPPE\3. generate
•	HAPPE\4. validate
•	HAPPE\packages
•	HAPPE\packages\eeglab2022.0
In the Set Path window that opens, use the Add with Subfolders button to add the following folders (Please note that if you are using a Mac, \ will be replaced with /):
•	HAPPE\scripts
•	HAPPE\files

It's possible that instead of HAPPE, the folder is named HAPPE-master. Same case with the Mac Quarantine steps, replace HAPPE with HAPPE-master (or whatever your HAPPE folder is named).

We will have an updated user guide as soon as the changes are made.
